
version: '3.8'

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app_container
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bank_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
